# Generated by Django 4.0.2 on 2024-03-11 18:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='exerciseComplete',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='exerciseGrade',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='exerciseName',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
