# Generated by Django 4.0.2 on 2024-03-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subject_exercisecomplete_subject_exercisegrade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
    ]
