# Generated by Django 4.0.2 on 2024-03-11 18:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_delete_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exerciseName', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150, null=True), blank=True, size=None)),
                ('exerciseComplete', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), blank=True, size=None)),
                ('exerciseGrade', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None)),
                ('student', models.ManyToManyField(limit_choices_to={'groups': 1}, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'groups': 2}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
