# Generated by Django 4.0.2 on 2024-03-11 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exerciseComplete',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='exerciseGrade',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='exerciseName',
        ),
        migrations.AddField(
            model_name='exercise',
            name='max_grade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='student',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups': 1}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='exercise',
            field=models.ManyToManyField(blank=True, to='main.exercise'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('name', 'student')},
        ),
    ]
