# Generated by Django 4.0.2 on 2024-03-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_subject_exercisecomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='complete',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
