# Generated by Django 4.0.2 on 2024-03-19 13:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_exercise_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to='uploads/<django.db.models.fields.related.ForeignKey>/'), blank=True, null=True, size=None),
        ),
    ]
