# Generated by Django 4.0.2 on 2024-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_exercise_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
