# Generated by Django 4.0.2 on 2024-03-21 08:19

import django.contrib.postgres.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_exercise_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='upload',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=main.models.user_directory_path), blank=True, null=True, size=None),
        ),
    ]
